from typing import List, Literal

from pydantic import BaseModel, Field


class CandidateAnalysis(BaseModel):
    """
    Structured output generated by the LLM after analyzing a candidate
    resume against a specific job description.

    This schema defines the format of the AI evaluation used in the system.
    It ensures that the language model returns standardized data that can
    be safely validated and stored in the database.

    The analysis includes:
    - A match score between the candidate and the job
    - A short overall opinion about the candidate
    - Main strengths relevant to the job
    - Main weaknesses or missing skills
    - Languages detected in the resume
    - The highest education level identified
    """

    score: float = Field(
        ge=0,
        le=100,
        description=(
            "Candidate score from 0 to 100 based on how well the "
            "resume matches the job description"
        ),
    )

    opinion: str = Field(
        description="Short overall evaluation of the candidate"
    )

    strengths: str = Field(
        description="Main strengths of the candidate related to the job"
    )

    weaknesses: str = Field(
        description="Main weaknesses or missing skills of the candidate"
    )

    languages: List[str] = Field(
        default_factory=list,
        description="Languages mentioned in the resume"
    )

    education_level: Literal[
        "High School",
        "Associate Degree",
        "Technical Degree",
        "Bachelor's Degree",
        "Postgraduate",
        "Master's Degree",
        "Doctorate",
        "Course / Certification",
        "Not Informed",
    ] = Field(
        description="Highest education level found in the resume"
    )